# This will create 3 mongodb Pods with statefulsets and persistent volume with persistent volume claim
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: k8s-voting-app
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      role: db
  template:
    metadata:
      labels:
        role: db
        env: demo
        replicaset: rs0.main
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: replicaset
                      operator: In
                      values:
                        - rs0.main
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo # providing the container name
          image: mongo:4.2 # it's image
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "rs0"
          ports:
            - containerPort: 27017 # ports where mongodb runs
          volumeMounts: # mounting the volume on some path with persistent Storage
            - name: mongodb-persistent-storage-claim # name of the persistent storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage-claim # name of the persistent storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2
        resources:
          requests:
            storage: 0.5Gi # request storage for 0.5 GB


  # Once we run this along with the pods it will create Storage Volume
