apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: k8s-voting-app
  labels:
    role: db
    env: demo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None # here we are specifying Headless service
  selector:
    role: db
